export default colors => ({
  name: "Borealis",
  type: "dark",
  colors: {
    "focusBorder": colors.teal,
    "foreground": colors.gallery,
    "widget.shadow": colors.swamp,
    "selection.background": colors.sherpaBlue,
    "descriptionForeground": colors.opal,
    "errorForeground": colors.aqua,
    "textBlockQuote.background": colors.sherpaBlue,
    "textBlockQuote.border": colors.sherpaBlue,
    "textCodeBlock.background": colors.sherpaBlue,
    "textLink.activeForeground": colors.gallery,
    "textLink.foreground": colors.candlelight,
    "textPreformat.foreground": colors.gallery,
    "textSeparator.foreground": colors.teal,
    "button.background": colors.sherpaBlue,
    "button.foreground": colors.opal,
    "button.hoverBackground": colors.deepTeal,
    "dropdown.background": colors.deepTeal,
    "dropdown.listBackground": colors.sherpaBlue,
    "dropdown.border": colors.deepTeal,
    "dropdown.foreground": colors.opal,
    "input.background": colors.sherpaBlue,
    "input.border": colors.sherpaBlue,
    "input.foreground": colors.gallery,
    "input.placeholderForeground": colors.mystic,
    "inputOption.activeBorder": colors.mystic,
    "inputValidation.errorBackground": colors.sherpaBlue,
    "inputValidation.errorBorder": colors.aqua,
    "inputValidation.infoBackground": colors.sherpaBlue,
    "inputValidation.infoBorder": colors.lightingYellow,
    "inputValidation.warningBackground": colors.sherpaBlue,
    "inputValidation.warningBorder": colors.malachite,
    "scrollbar.shadow": colors.deepTeal,
    "scrollbarSlider.activeBackground": colors.translucent9,
    "scrollbarSlider.background": colors.translucent9,
    "scrollbarSlider.hoverBackground": colors.translucent9,
    "badge.foreground": colors.deepTeal,
    "badge.background": colors.candlelight,
    "progressBar.background": colors.sherpaBlue,
    "list.activeSelectionBackground": colors.deepTeal,
    "list.activeSelectionForeground": colors.candlelight,
    "list.errorForeground": colors.aqua,
    "list.warningForeground": colors.malachite,
    "list.dropBackground": colors.translucent,
    "list.focusBackground": colors.deepTeal,
    "list.focusForeground": colors.gallery,
    "list.highlightForeground": colors.gallery,
    "list.hoverBackground": colors.darkDeepTeal,
    "list.hoverForeground": colors.gallery,
    "list.inactiveSelectionBackground": colors.deepTeal,
    "list.inactiveSelectionForeground": colors.candlelight,
    "list.inactiveFocusBackground": colors.deepTeal,
    "list.invalidItemForeground": colors.aqua,
    "activityBar.background": colors.swamp,
    "activityBar.dropBackground": colors.translucent,
    "activityBar.foreground": colors.opal,
    "activityBar.border": colors.swamp,
    "activityBarBadge.background": colors.candlelight,
    "activityBarBadge.foreground": colors.deepTeal,
    "sideBar.background": colors.darkDeepTeal,
    "sideBar.foreground": colors.opal,
    "sideBar.border": colors.swamp,
    "sideBar.dropBackground": colors.translucent,
    "sideBarTitle.foreground": colors.mystic,
    "sideBarSectionHeader.background": colors.darkDeepTeal,
    "sideBarSectionHeader.foreground": colors.teal,
    "editorGroup.background": colors.swamp,
    "editorGroup.border": colors.darkDeepTeal,
    "editorGroup.dropBackground": colors.translucent,
    "editorGroupHeader.noTabsBackground": colors.deepTeal,
    "editorGroupHeader.tabsBackground": colors.deepTeal,
    "editorGroupHeader.tabsBorder": colors.deepTeal,
    "tab.activeBackground": colors.deepTeal,
    "tab.activeForeground": colors.candlelight,
    "tab.border": colors.deepTeal,
    "tab.activeBorder": colors.candlelight,
    "tab.unfocusedActiveBorder": colors.opal,
    "tab.inactiveBackground": colors.deepTeal,
    "tab.inactiveForeground": colors.opal,
    "tab.unfocusedActiveForeground": colors.sweetPink,
    "tab.unfocusedInactiveForeground": colors.opal,
    "tab.hoverBackground": colors.deepTeal,
    "tab.unfocusedHoverBackground": colors.deepTeal,
    "tab.hoverBorder": colors.mystic,
    "tab.unfocusedHoverBorder": colors.deepTeal,
    "editor.background": colors.deepTeal,
    "editor.foreground": colors.gallery,
    "editorLineNumber.foreground": colors.mystic,
    "editorLineNumber.activeForeground": colors.sweetPink,
    "editorCursor.background": colors.translucent8,
    "editorCursor.foreground": colors.gallery,
    "editor.selectionBackground": colors.sherpaBlue,
    "editor.inactiveSelectionBackground": colors.translucent3,
    "editor.selectionHighlightBackground": colors.translucent2,
    "editor.selectionHighlightBorder": colors.translucent8,
    "editor.wordHighlightBackground": colors.translucent2,
    "editor.wordHighlightBorder": colors.translucent8,
    "editor.wordHighlightStrongBackground": colors.translucent2,
    "editor.wordHighlightStrongBorder": colors.translucent8,
    "editor.findMatchBackground": colors.translucent2,
    "editor.findMatchBorder": colors.candlelight,
    "editor.findMatchHighlightBackground": colors.translucent2,
    "editor.findMatchHighlightBorder": colors.translucent8,
    "editor.findRangeHighlightBackground": colors.translucent3,
    "editor.findRangeHighlightBorder": colors.translucent8,
    "editor.hoverHighlightBackground": colors.translucent3,
    "editor.lineHighlightBackground": colors.translucent3,
    "editor.lineHighlightBorder": colors.translucent8,
    "editorLink.activeForeground": colors.lightingYellow,
    "editor.rangeHighlightBackground": colors.sherpaBlue,
    "editor.rangeHighlightBorder": colors.sherpaBlue,
    "editorWhitespace.foreground": colors.mystic,
    "editorIndentGuide.background": colors.sherpaBlue,
    "editorRuler.foreground": colors.mystic,
    "editorCodeLens.foreground": colors.teal,
    "editorBracketMatch.background": colors.deepTeal,
    "editorBracketMatch.border": colors.teal,
    "editorError.foreground": colors.aqua,
    "editorError.border": colors.translucent8,
    "editorWarning.foreground": colors.malachite,
    "editorWarning.border": colors.translucent8,
    "editorInfo.foreground": colors.lightingYellow,
    "editorInfo.border": colors.deepTeal,
    "editorHint.foreground": colors.lavenderRose,
    "editorHint.border": colors.deepTeal,
    "editorGutter.background": colors.deepTeal,
    "editorGutter.modifiedBackground": colors.malachite,
    "editorGutter.addedBackground": colors.perfume,
    "editorGutter.deletedBackground": colors.aqua,
    "diffEditor.insertedTextBackground": colors.translucent4,
    "diffEditor.insertedTextBorder": colors.translucent8,
    "diffEditor.removedTextBackground": colors.translucent6,
    "diffEditor.removedTextBorder": colors.translucent8,
    "editorWidget.background": colors.sherpaBlue,
    "editorWidget.border": colors.sherpaBlue,
    "editorSuggestWidget.background": colors.sherpaBlue,
    "editorSuggestWidget.border": colors.sherpaBlue,
    "editorSuggestWidget.foreground": colors.sweetPink,
    "editorSuggestWidget.highlightForeground": colors.gallery,
    "editorSuggestWidget.selectedBackground": colors.teal,
    "editorHoverWidget.background": colors.sherpaBlue,
    "editorHoverWidget.border": colors.deepTeal,
    "debugExceptionWidget.background": colors.sherpaBlue,
    "debugExceptionWidget.border": colors.deepTeal,
    "editorMarkerNavigation.background": colors.sherpaBlue,
    "editorMarkerNavigationError.background": colors.aqua,
    "editorMarkerNavigationWarning.background": colors.malachite,
    "editorMarkerNavigationInfo.background": colors.lightingYellow,
    "peekView.border": colors.deepTeal,
    "peekViewEditor.background": colors.sherpaBlue,
    "peekViewEditorGutter.background": colors.sherpaBlue,
    "peekViewEditor.matchHighlightBackground": colors.mystic,
    "peekViewResult.background": colors.sherpaBlue,
    "peekViewResult.fileForeground": colors.opal,
    "peekViewResult.lineForeground": colors.opal,
    "peekViewResult.matchHighlightBackground": colors.mystic,
    "peekViewResult.selectionBackground": colors.sherpaBlue,
    "peekViewResult.selectionForeground": colors.gallery,
    "peekViewTitle.background": colors.sherpaBlue,
    "peekViewTitleDescription.foreground": colors.opal,
    "peekViewTitleLabel.foreground": colors.gallery,
    "merge.currentHeaderBackground": colors.translucent7,
    "merge.currentContentBackground": colors.translucent6,
    "merge.incomingHeaderBackground": colors.translucent5,
    "merge.incomingContentBackground": colors.translucent4,
    "merge.border": colors.deepTeal,
    "merge.commonHeaderBackground": colors.translucent2,
    "merge.commonContentBackground": colors.translucent3,
    "editorOverviewRuler.border": colors.deepTeal,
    "editorOverviewRuler.currentContentForeground": colors.sherpaBlue,
    "editorOverviewRuler.incomingContentForeground": colors.sherpaBlue,
    "editorOverviewRuler.findMatchForeground": colors.translucent2,
    "editorOverviewRuler.rangeHighlightForeground": colors.translucent2,
    "editorOverviewRuler.selectionHighlightForeground": colors.translucent2,
    "editorOverviewRuler.wordHighlightForeground": colors.translucent2,
    "editorOverviewRuler.wordHighlightStrongForeground": colors.translucent2,
    "editorOverviewRuler.modifiedForeground": colors.malachite,
    "editorOverviewRuler.addedForeground": colors.perfume,
    "editorOverviewRuler.deletedForeground": colors.aqua,
    "editorOverviewRuler.errorForeground": colors.aqua,
    "editorOverviewRuler.warningForeground": colors.malachite,
    "editorOverviewRuler.infoForeground": colors.lightingYellow,
    "panel.background": colors.darkDeepTeal,
    "panel.border": colors.candlelight,
    "panel.dropBackground": colors.translucent,
    "panelTitle.activeBorder": colors.candlelight,
    "panelTitle.activeForeground": colors.candlelight,
    "panelTitle.inactiveForeground": colors.opal,
    "statusBar.background": colors.darkDeepTeal,
    "statusBar.foreground": colors.teal,
    "statusBar.border": colors.swamp,
    "statusBar.debuggingBackground": colors.teal,
    "statusBar.debuggingForeground": colors.gallery,
    "statusBar.debuggingBorder": colors.darkDeepTeal,
    "statusBar.noFolderBackground": colors.darkDeepTeal,
    "statusBar.noFolderForeground": colors.teal,
    "statusBar.noFolderBorder": colors.swamp,
    "statusBarItem.activeBackground": colors.deepTeal,
    "statusBarItem.hoverBackground": colors.deepTeal,
    "statusBarItem.prominentBackground": colors.sherpaBlue,
    "statusBarItem.prominentHoverBackground": colors.sherpaBlue,
    "titleBar.activeBackground": colors.darkDeepTeal,
    "titleBar.activeForeground": colors.opal,
    "titleBar.inactiveBackground": colors.darkDeepTeal,
    "titleBar.inactiveForeground": colors.mystic,
    "titleBar.border": colors.swamp,
    "notificationCenter.border": colors.sherpaBlue,
    "notificationCenterHeader.foreground": colors.opal,
    "notificationCenterHeader.background": colors.sherpaBlue,
    "notificationToast.border": colors.sherpaBlue,
    "notifications.foreground": colors.sweetPink,
    "notifications.background": colors.sherpaBlue,
    "notifications.border": colors.sherpaBlue,
    "notificationLink.foreground": colors.candlelight,
    "extensionButton.prominentForeground": colors.gallery,
    "extensionButton.prominentBackground": colors.sherpaBlue,
    "extensionButton.prominentHoverBackground": colors.mystic,
    "pickerGroup.border": colors.deepTeal,
    "pickerGroup.foreground": colors.mystic,
    "terminal.background": colors.darkDeepTeal,
    "terminal.foreground": colors.gallery,
    "terminal.ansiBlack": colors.swamp,
    "terminal.ansiBlue": colors.jordyBlue,
    "terminal.ansiBrightBlack": colors.sherpaBlue,
    "terminal.ansiBrightBlue": colors.skyBlue,
    "terminal.ansiBrightCyan": colors.aqua,
    "terminal.ansiBrightGreen": colors.green,
    "terminal.ansiBrightMagenta": colors.lavenderRose,
    "terminal.ansiBrightRed": colors.persimmmon,
    "terminal.ansiBrightWhite": colors.mystic,
    "terminal.ansiBrightYellow": colors.candlelight,
    "terminal.ansiCyan": colors.aqua,
    "terminal.ansiGreen": colors.malachite,
    "terminal.ansiMagenta": colors.perfume,
    "terminal.ansiRed": colors.sweetPink,
    "terminal.ansiWhite": colors.gallery,
    "terminal.ansiYellow": colors.lightingYellow,
    "terminal.selectionBackground": colors.translucent2,
    "terminalCursor.background": colors.translucent8,
    "terminalCursor.foreground": colors.gallery,
    "debugToolBar.background": colors.darkDeepTeal,
    "welcomePage.buttonBackground": colors.sherpaBlue,
    "welcomePage.buttonHoverBackground": colors.mystic,
    "walkThrough.embeddedEditorBackground": colors.deepTeal,
    "gitDecoration.modifiedResourceForeground": colors.perfume,
    "gitDecoration.deletedResourceForeground": colors.aqua,
    "gitDecoration.untrackedResourceForeground": colors.malachite,
    "gitDecoration.ignoredResourceForeground": colors.mystic,
    "gitDecoration.conflictingResourceForeground": colors.malachite
  },
  tokenColors: [
    {
      name: "COMMENT",
      scope: [
        "comment",
        "punctuation.definition.comment",
        "punctuation.definition.tag",
        "comment.block.documentation punctuation.definition.bracket"
      ],
      settings: {
        foreground: colors.teal
      }
    },
    {
      name: "TEXT",
      scope: [
        "constant.character",
        "constant.escape",
        "text.html.markdown",
        "punctuation.definition.list_item",
        "keyword.begin.tag.ejs",
        "constant.name.attribute.tag.pug",
        "source.clojure meta.symbol",
        "constant.other.description.jsdoc",
        "keyword.other.array.phpdoc.php",
        "keyword.operator.other.powershell",
        "meta.link.inline punctuation.definition.string",
        "source.sql",
        "source meta.brace",
        "source punctuation",
        "text.html punctuation",
        "markup meta punctuation.definition",
        "meta.bracket.julia",
        "meta.array.julia",
        "punctuation.separator.key-value"
      ],
      settings: {
        foreground: colors.gallery
      }
    },
    {
      name: "KEYWORD",
      scope: [
        "keyword",
        "keyword.control",
        "keyword.other.template",
        "keyword.other.substitution",
        "storage.modifier",
        "meta.tag.sgml",
        "punctuation.accessor",
        "constant.other.color",
        "entity.name.section",
        "markup.heading",
        "markup.heading punctuation.definition",
        "entity.other.attribute-name.pseudo-class",
        "entity.other.attribute-name.pseudo-element",
        "tag.decorator.js entity.name.tag.js",
        "tag.decorator.js punctuation.definition.tag.js",
        "storage.type.function.pug",
        "text.pug storage.type",
        "text.pug meta.tag.other",
        "source.clojure storage.control",
        "meta.expression.clojure",
        "punctuation.separator.slice.python",
        "punctuation.separator.question-mark.cs",
        "punctuation.definition.parameters.varargs",
        "source.go keyword.operator",
        "punctuation.definition.directive.c",
        "punctuation.separator.pointer-access",
        "punctuation.separator.other.ruby",
        "keyword.package.go",
        "keyword.import.go",
        "punctuation.definition.keyword",
        "storage.type.modifier.cpp",
        "punctuation.separator.hash.cs",
        "variable.parameter.rest.lua",
        "entity.other.attribute-name.pseudo-class.css punctuation.definition.entity.css",
        "entity.other.attribute-name.pseudo-element.css punctuation.definition.entity.css",
        "source.kotlin storage.type.import",
        "source.kotlin storage.type.package",
        "constant.string.documentation.powershell",
        "punctuation.section.directive",
        "storage.type.rust",
        "punctuation.definition.attribute",
        "punctuation.definition.preprocessor",
        "punctuation.separator.namespace",
        "punctuation.separator.method"
      ],
      settings: {
        foreground: colors.sweetPink
      }
    },
    {
      name: "VARIABLE",
      scope: [
        "variable",
        "variable.object",
        "variable.other",
        "variable.parameter",
        "support",
        "string constant.other.placeholder",
        "source.css.scss variable",
        "entity.name.module",
        "variable.import.parameter",
        "variable.other.class",
        "meta.toc-list.id.html",
        "source.json meta.structure.dictionary.json support.type.property-name.json",
        "markup.list",
        "meta.var.clojure",
        "source.cs entity.name.variable",
        "source.java meta.class.body.java",
        "entity.name.package.go",
        "source.c",
        "source.cpp",
        "source.go",
        "source.python",
        "meta.function-call.arguments.python",
        "source.ruby",
        "source.coffee.embedded.source",
        "source.coffee",
        "storage.modifier.import",
        "storage.modifier.package",
        "storage.type.annotation",
        "punctuation.definition.annotation",
        "source.groovy.embedded.source",
        "punctuation.definition.variable",
        "source.powershell",
        "string.quoted.interpolated.vala constant.character.escape.vala",
        "source.apacheconf",
        "source.objc",
        "source.crystal",
        "string.quoted.double.kotlin entity.string.template.element.kotlin",
        "entity.name.package.kotlin",
        "meta.template.expression.kotlin",
        "parameter.variable.function",
        "variable.other.constant.elixir",
        "source.elixir.embedded.source",
        "source.sql.embedded",
        "punctuation.definition.placeholder",
        "source.swift",
        "source.julia"
      ],
      settings: {
        foreground: colors.lightingYellow
      }
    },
    {
      name: "ANNOTATION",
      scope: [
        "support.variable.property",
        "constant.other.symbol.hashkey.ruby",
        "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
        "entity.other.attribute-name.id.css",
        "entity.other.attribute-name.id.css punctuation.definition.entity.css",
        "entity.name.type.annotation.kotlin",
        "support.type.primitive",
        "meta.type.parameters entity.name.type",
        "meta.type.annotation entity.name.type",
        "punctuation.definition.typeparameters",
        "source.python support.type.python",
        "comment.block.documentation.phpdoc.php keyword.other.type.php",
        "storage.type.php",
        "keyword.type.cs",
        "storage.type.cs",
        "storage.type.c",
        "storage.type.objc",
        "punctuation.definition.storage.type.objc",
        "markup punctuation.definition",
        "storage.type.powershell",
        "comment.block.documentation entity.name.type",
        "source.java storage.type",
        "storage.type.primitive",
        "source.groovy storage.type",
        "storage.type.r",
        "source.haskell storage.type",
        "punctuation.separator.clause-head-body",
        "source.go storage.type",
        "storage.type.core.rust",
        "storage.class.std.rust",
        "storage.modifier.lifetime.rust",
        "entity.name.lifetime.rust",
        "support.type.swift",
        "support.type.vb",
        "entity.name.type.kotlin",
        "support.type.julia"
      ],
      settings: {
        foreground: colors.lavenderRose
      }
    },
    {
      name: "CONSTANT",
      scope: [
        "constant",
        "variable.other.constant",
        "support.constant",
        "punctuation.definition.entity",
        "constant.character.entity",
        "support.variable.magic",
        "entity.other.attribute-name",
        "markup.quote",
        "entity.name.type.type-parameter.cs",
        "punctuation.bracket.angle",
        "entity.name.function.preprocessor.c",
        "support.variable.lua",
        "storage.type.scala",
        "entity.helper.apacheconf",
        "source.vala storage.type",
        "variable.language.crystal",
        "punctuation.definition.constant",
        "support.constant punctuation.definition.variable"
      ],
      settings: {
        foreground: colors.candlelight
      }
    },
    {
      name: "TAG",
      scope: [
        "variable.language",
        "variable.parameter.function.language.special",
        "markup.bold",
        "markup.italic",
        "punctuation.definition.italic",
        "punctuation.definition.bold",
        "entity.name.tag",
        "variable.language punctuation.definition.variable.php",
        "keyword.control.clojure",
        "support.type.exception.python",
        "keyword.other.this.cs",
        "keyword.other.base.cs",
        "keyword.other.var.cs",
        "storage.modifier.super",
        "source.go keyword",
        "keyword.function.go",
        "meta.separator",
        "keyword.other.fn.rust",
        "storage.modifier.static.rust",
        "source.r meta.function.r keyword.control.r",
        "storage.type.def",
        "meta.class.identifier storage.modifier",
        "source.scala keyword.declaration",
        "storage.type",
        "comment.block.documentation punctuation.definition.block.tag",
        "comment.block.documentation punctuation.definition.inline.tag",
        "entity.tag.apacheconf",
        "keyword.other.julia",
        "source.julia storage.modifier",
        "constant.language.empty-list.haskell",
        "keyword.declaration.scala",
        "meta.function.powershell storage.type.powershell",
        "keyword.control.fun",
        "punctuation.terminator.function",
        "keyword.other.rust",
        "keyword.other.declaration-specifier.swift",
        "keyword.control.function-end.lua",
        "keyword.control.class",
        "keyword.control.def"
      ],
      settings: {
        foreground: colors.monaLisa
      }
    },
    {
      name: "STRING",
      scope: [
        "string",
        "punctuation.definition.string",
        "source.css support.constant",
        "entity.name.import.go"
      ],
      settings: {
        foreground: colors.malachite
      }
    },
    {
      name: "STRINGINTERPOLATED",
      scope: [
        "string.template",
        "punctuation.definition.string.template",
        "string.interpolated.python string.quoted.single.python",
        "string.quoted.double.heredoc",
        "string.quoted.interpolated.vala",
        "string.quoted.interpolated.vala punctuation.definition.string",
        "string.regexp.apacheconf",
        "markup.inline.raw.string",
        "markup.inline.raw punctuation.definition.raw",
        "string.quoted.double.interpolated.crystal",
        "string.quoted.double.interpolated.crystal punctuation.definition.string"
      ],
      settings: {
        foreground: colors.green
      }
    },
    {
      name: "NUMBER",
      scope: [
        "constant.numeric",
        "constant.language",
        "punctuation.separator.decimal.period.php",
        "keyword.operator.null-conditional.cs",
        "punctuation.separator.question-mark.cs",
        "constant.integer.apacheconf",
        "keyword.operator.nullable-type",
        "constant.language punctuation.definition.variable"
      ],
      settings: {
        foreground: colors.perfume
      }
    },
    {
      name: "FUNCTION",
      scope: [
        "variable.function",
        "source.css support.type.property-name",
        "source.sass support.type.property-name",
        "source.scss support.type.property-name",
        "source.less support.type.property-name",
        "source.stylus support.type.property-name",
        "source.postcss support.type.property-name",
        "keyword.other.unit",
        "entity.name.function",
        "string.other.link",
        "markup.link",
        "support.type.vendored",
        "support.other.variable",
        "meta.function-perfume.generic.python",
        "meta.method-call.groovy meta.method.groovy",
        "meta.class.body.groovy meta.method.body.java storage.type.groovy",
        "punctuation.decorator.ts",
        "punctuation.definition.decorator",
        "support.function.any-method"
      ],
      settings: {
        foreground: colors.aqua
      }
    },
    {
      name: "SUPPORT",
      scope: [
        "entity.name",
        "entity.other",
        "support.orther.namespace.use.php",
        "meta.use.php",
        "support.other.namespace.php",
        "support.type",
        "support.class",
        "punctuation.definition.parameters",
        "support.function",
        "support.function.construct",
        "markup.changed.git_gutter",
        "markup.underline.link",
        "markup.underline.link.image",
        "markup.underline",
        "meta.symbol.namespace.clojure",
        "entity.name.type.namespace.cs",
        "support.class.dart",
        "entity.mime-type.apacheconf",
        "keyword.operator.function.infix",
        "entity.name.function.infix",
        "entity.name.function.call.kotlin"
      ],
      settings: {
        foreground: colors.skyBlue
      }
    },
    {
      name: "MISC",
      scope: [
        "source.js constant.other.object.key.js string.unquoted.label.js",
        "source.js punctuation.section.embedded",
        "punctuation.definition.template-expression",
        "support.class",
        "entity.name.type",
        "storage.type.string.python",
        "string.interpolated.pug",
        "support.constant.handlebars",
        "source.clojure punctuation.section.set",
        "source.clojure punctuation.section.metadata",
        "entity.global.clojure",
        "source.python meta.function-call.python support.type.python",
        "constant.character.format.placeholder.other.python",
        "entity.other.inherited-class.python",
        "punctuation.definition.interpolation",
        "constant.other.placeholder.go",
        "constant.other.placeholder.c",
        "punctuation.section.embedded.begin.ruby",
        "punctuation.section.embedded.end.ruby source.ruby",
        "support.constant.math",
        "entity.namespace.r",
        "meta.method-call.groovy storage.type.groovy",
        "entity.name.function-table.lua",
        "source.scala entity.name.class.declaration",
        "constant.character.escape",
        "support.function.macro.julia",
        "string.replacement.apacheconf",
        "storage.modifier.using.vala",
        "constant.other.haskell",
        "source.objc entity.name.tag",
        "string.quoted.other.literal.upper.crystal punctuation.definition.string",
        "meta.embedded.line.crystal punctuation.section.embedded",
        "meta.embedded.line.crystal punctuation.section.embedded source.crystal",
        "source.scala entity.name.class",
        "punctuation.section.embedded",
        "punctuation.section.tag",
        "punctuation.section.embedded source.swift"
      ],
      settings: {
        foreground: colors.jordyBlue
      }
    },
    {
      name: "INVALID",
      scope: ["invalid", "invalid.illegal"],
      settings: {
        foreground: colors.persimmmon
      }
    },
    {
      name: "ITALIC",
      scope: [
        "comment",
        "storage.modifier",
        "punctuation.definition.comment",
        "entity.other",
        "variable.language",
        "support.type.vendored",
        "support.constant.vendored",
        "markup.quote",
        "markup.italic",
        "tag.decorator.js entity.name.tag.js",
        "tag.decorator.js punctuation.definition.tag.js",
        "keyword.control.clojure",
        "source.clojure meta.symbol.dynamic",
        "keyword.other.this.cs",
        "keyword.other.base.cs",
        "variable.other.member.c",
        "storage.class.std.rust",
        "support.type.core.rust",
        "variable.other.object.property",
        "variable.other.property",
        "source.r meta.function.r keyword.control.r",
        "comment.line.roxygen.r keyword",
        "comment.line.roxygen.r variable.parameter.r",
        "keyword.control.inheritance.coffee",
        "comment.block.documentation.phpdoc.php keyword",
        "keyword.other.array.phpdoc.php",
        "storage.type.modifier",
        "comment.block.javadoc.java keyword",
        "comment.block.javadoc.java variable.parameter.java",
        "keyword.operator.documentation.powershell",
        "variable.other.table.property.lua",
        "storage.type.scala",
        "variable.parameter.function.language.special",
        "comment.block.documentation.scala keyword",
        "comment.block.documentation.scala variable.parameter",
        "support.function.builtin.go",
        "constant.other.symbol.hashkey.ruby",
        "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
        "constant.other.symbol.ruby",
        "source.vala storage.type.generic",
        "variable.other.crystal",
        "constant.other.table-name",
        "constant.other.placeholder",
        "variable.other.field",
        "keyword.function.go",
        "entity.alias.import.go",
        "source.swift keyword.other.declaration-specifier",
        "support.variable.swift",
        "keyword.other.capture-specifier"
      ],
      settings: {
        fontStyle: "italic"
      }
    },
    {
      name: "BOLD",
      scope: [
        "keyword",
        "keyword.control",
        "keyword.operator",
        "keyword.other.template",
        "keyword.other.substitution",
        "storage.type.function.arrow",
        "constant.other.color",
        "punctuation.accessor",
        "entity.name.section",
        "markup.bold",
        "markup.bold string",
        "markdown.heading",
        "markup.inline.raw punctuation.definition.raw",
        "markup.heading",
        "storage.type.function.pug",
        "storage.type.function.python",
        "punctuation.definition.typeparameters",
        "storage.type.annotation",
        "punctuation.bracket.angle",
        "keyword.other.new",
        "punctuation.separator.question-mark.cs",
        "storage.type.generic.wildcard",
        "source.go keyword.operator",
        "punctuation.separator.namespace",
        "constant.other.symbol.ruby punctuation.definition.constant.ruby",
        "variable.parameter",
        "support.function.builtin.rust",
        "storage.type.function.coffee",
        "source.cs entity.name.variable.parameter",
        "punctuation.separator.hash.cs",
        "constant.other.symbol.ruby punctuation.definition.constant.ruby",
        "constant.other.symbol.hashkey.ruby punctuation.definition.constant.ruby",
        "meta.function.parameters variable.other",
        "keyword.declaration.scala",
        "entity.name.type.annotation.kotlin",
        "storage.type.function.kotlin",
        "support.type.primitive",
        "source.python support.type.python",
        "storage.type.php",
        "keyword.type.cs",
        "storage.type.objc",
        "parameter.variable.function",
        "markup punctuation.definition",
        "storage.type.primitive",
        "punctuation.section.directive",
        "punctuation.definition.preprocessor",
        "punctuation.definition.variable",
        "punctuation.separator.method"
      ],
      settings: {
        fontStyle: "bold"
      }
    },
    {
      name: "BOLD-ITALIC",
      scope: [
        "markup.bold markup.italic",
        "markup.italic markup.bold",
        "markup.quote markup.bold",
        "markup.bold markup.italic string",
        "markup.italic markup.bold string",
        "markup.quote markup.bold string",
        "text.html punctuation.section.embedded",
        "variable.other.c",
        "meta.function.constructor.cpp entity.name.function.cpp",
        "meta.function.destructor.cpp entity.name.function.cpp",
        "storage.modifier.lifetime.rust",
        "entity.name.lifetime.rust",
        "source.rust meta.attribute.rust",
        "meta.attribute.id entity.other.attribute-name",
        "keyword.other.fn.rust"
      ],
      settings: {
        fontStyle: "bold italic"
      }
    },
    {
      name: "NORMAL",
      scope: [
        "keyword.begin.tag.ejs",
        "source.python meta.function.decorator.python support.type.python",
        "source.cs keyword.other",
        "keyword.other.var.cs",
        "source.go keyword",
        "storage.modifier.static.rust",
        "variable.parameter.r",
        "variable.parameter.handlebars",
        "storage.modifier.import",
        "storage.modifier.package",
        "meta.class.identifier storage.modifier",
        "keyword.operator.other.powershell",
        "source.lua storage.type.function",
        "source.scala keyword.declaration",
        "source.css variable.parameter",
        "storage.type.primitive.dart",
        "string.interpolated variable.parameter",
        "source.apacheconf keyword",
        "keyword.other.julia",
        "storage.modifier.using.vala",
        "source.objc keyword.other.property.attribute",
        "source.sql keyword.other",
        "keyword.other.using.vala",
        "keyword.operator.function.infix",
        "keyword.control.directive",
        "keyword.other.rust",
        "keyword.other.declaration-specifier.swift",
        "entity.name.function.swift",
        "keyword.control.function-end.lua",
        "keyword.control.class",
        "keyword.control.def"
      ],
      settings: {
        fontStyle: ""
      }
    }
  ]
});
